# Generated by Django 3.1.6 on 2021-02-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='publishDate',
            field=models.DateTimeField(),
        ),
    ]
